### ISSUE TITLE
mqtt_Publish_Dummy_Data.py - SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by aisbergde** [pradeesi/Store_MQTT_Data_in_Database#3]
when I call the script I get an error:
mqtt_Publish_Dummy_Data.py", line 27
    print "Unable to connect to MQTT Broker..."
                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unable to connect to MQTT Broker...")?

I am working in Windows

**Comment by arnkmar** [comment]
The issue you are facing is due to the python version mismatch. The code is developed for Python v2.7. 

Either use Pyhton 2.7 or add the missing parentheses as the error message states.

**Comment by aisbergde** [comment]
Yes, I understand this and I added them.
